services:
    app:
        build: .
        container_name: <container name>
        ports:
            - '3000:3000'
        volumes:
            - ./app:/app # directory web/app
        networks:
            - default
        stdin_open: true
        tty: true
        environment:
            - CHOKIDAR_USEPOLLING=true # for autodetection
